// WHO SMART Guidelines knowledge graph -- ALL LAYERS, in dependency order.
// Generated by tools/build-exports.mjs. Do not edit; edit the per-layer JSON.
//
// RUN AGAINST A USER DATABASE, NOT `system`:
//     :use neo4j                              (Neo4j Browser, or your database's name)
//     cypher-shell -d neo4j -f ontology/all.cypher
//
// In Neo4j Browser, turn on "Enable multi statement query editor" in Settings before
// pasting -- otherwise only the first statement runs.
//
// l1 -> l2 -> l2-bpmn -> l2-dmn -> l3. Loading a layer before the ones it imports silently drops the
// edges that reach into them, because Cypher does not treat an empty MATCH as an error.

// WHO SMART Guidelines knowledge graph -- L1 ONTOLOGY (type graph).
// Generated by tools/build-exports.mjs. Do not edit; edit the ontology JSON.
//
// These are CLASSES and LICENSED EDGES, not DAK instance data. Loading this gives you the
// schema to explore; a DAK's own graph is generated by that DAK's IG build. See docs/STORAGE.md.
//
// Every statement is MERGE, so re-running is safe.
//
// RUN THIS AGAINST A USER DATABASE, NOT `system`. The CREATE CONSTRAINT below is rejected
// with "can only be executed in a user database" if `system` is selected, which is where
// Neo4j Browser can land you after connecting. Switch first:
//
//     :use neo4j                                    (Browser, or your database's name)
//     cypher-shell -d neo4j -f <this file>           (shell)

CREATE CONSTRAINT kgclass_id IF NOT EXISTS
FOR (c:KGClass) REQUIRE c.id IS UNIQUE;

MERGE (:KGClass:Source {id:'publication', name:'Publication', kind:'Source', layer:'l1', iri:'http://smart.who.int/kg/publication'});
MERGE (:KGClass:Source {id:'publication-section', name:'Publication section', kind:'Source', layer:'l1', iri:'http://smart.who.int/kg/publication-section'});
MERGE (:KGClass:Concept {id:'recommendation', name:'Recommendation', kind:'Concept', layer:'l1', iri:'http://smart.who.int/kg/recommendation'});
MERGE (:KGClass:Concept {id:'remark', name:'Remark', kind:'Concept', layer:'l1', iri:'http://smart.who.int/kg/remark'});
MERGE (:KGClass:Concept {id:'evidence', name:'Evidence', kind:'Concept', layer:'l1', iri:'http://smart.who.int/kg/evidence'});
MERGE (:KGClass:Concept {id:'population', name:'Population', kind:'Concept', layer:'l1', iri:'http://smart.who.int/kg/population'});
MERGE (:KGClass:Concept {id:'intervention', name:'Intervention', kind:'Concept', layer:'l1', iri:'http://smart.who.int/kg/intervention'});
MERGE (:KGClass:Concept {id:'comparator', name:'Comparator', kind:'Concept', layer:'l1', iri:'http://smart.who.int/kg/comparator'});
MERGE (:KGClass:Concept {id:'outcome', name:'Outcome', kind:'Concept', layer:'l1', iri:'http://smart.who.int/kg/outcome'});
MERGE (:KGClass:Concept {id:'health-intervention', name:'Health intervention', kind:'Concept', layer:'l1', iri:'http://smart.who.int/kg/health-intervention'});
MERGE (:KGClass:Concept {id:'schedule', name:'Schedule', kind:'Concept', layer:'l1', iri:'http://smart.who.int/kg/schedule'});
MERGE (:KGClass:Concept {id:'schedule-entry', name:'Schedule entry', kind:'Concept', layer:'l1', iri:'http://smart.who.int/kg/schedule-entry'});
MERGE (:KGClass:Concept {id:'indicator', name:'Indicator', kind:'Concept', layer:'l1', iri:'http://smart.who.int/kg/indicator'});
MERGE (:KGClass:Reference {id:'terminology-code', name:'Terminology code', kind:'Reference', layer:'l1', iri:'http://smart.who.int/kg/terminology-code'});
MERGE (:KGClass:Reference {id:'citation', name:'Citation', kind:'Reference', layer:'l1', iri:'http://smart.who.int/kg/citation'});
MERGE (:KGClass:Reference {id:'external-artifact', name:'External artefact', kind:'Reference', layer:'l1', iri:'http://smart.who.int/kg/external-artifact'});

MATCH (s:KGClass {id:'publication'}), (t:KGClass {id:'publication-section'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'publication-section'}), (t:KGClass {id:'recommendation'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'publication'}), (t:KGClass {id:'recommendation'}) MERGE (s)-[:CONTAINS {predicate:'contains', qualifier:'unsectioned'}]->(t);
MATCH (s:KGClass {id:'publication'}), (t:KGClass {id:'publication'}) MERGE (s)-[:SUPERSEDES {predicate:'supersedes'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'recommendation'}) MERGE (s)-[:REFINES {predicate:'refines'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'population'}) MERGE (s)-[:HASPOPULATION {predicate:'hasPopulation'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'intervention'}) MERGE (s)-[:HASINTERVENTION {predicate:'hasIntervention'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'comparator'}) MERGE (s)-[:HASCOMPARATOR {predicate:'hasComparator'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'outcome'}) MERGE (s)-[:HASOUTCOME {predicate:'hasOutcome'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'evidence'}) MERGE (s)-[:SUPPORTEDBY {predicate:'supportedBy'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'remark'}) MERGE (s)-[:HASREMARK {predicate:'hasRemark'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'health-intervention'}) MERGE (s)-[:RECOMMENDS {predicate:'recommends'}]->(t);
MATCH (s:KGClass {id:'schedule'}), (t:KGClass {id:'publication'}) MERGE (s)-[:DEFINEDIN {predicate:'definedIn'}]->(t);
MATCH (s:KGClass {id:'schedule'}), (t:KGClass {id:'schedule-entry'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'schedule-entry'}), (t:KGClass {id:'health-intervention'}) MERGE (s)-[:SCHEDULES {predicate:'schedules'}]->(t);
MATCH (s:KGClass {id:'schedule-entry'}), (t:KGClass {id:'recommendation'}) MERGE (s)-[:DERIVEDFROM {predicate:'derivedFrom'}]->(t);
MATCH (s:KGClass {id:'indicator'}), (t:KGClass {id:'publication'}) MERGE (s)-[:DEFINEDIN {predicate:'definedIn'}]->(t);
MATCH (s:KGClass {id:'indicator'}), (t:KGClass {id:'health-intervention'}) MERGE (s)-[:MEASURES {predicate:'measures'}]->(t);
MATCH (s:KGClass {id:'indicator'}), (t:KGClass {id:'recommendation'}) MERGE (s)-[:DERIVEDFROM {predicate:'derivedFrom'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'population'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'intervention'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'outcome'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'schedule-entry'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'indicator'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'health-intervention'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'health-intervention'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CLASSIFIEDAS {predicate:'classifiedAs', qualifier:'CDHI'}]->(t);
MATCH (s:KGClass {id:'citation'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:APPEARSIN {predicate:'appearsIn'}]->(t);
MATCH (s:KGClass {id:'citation'}), (t:KGClass {id:'publication'}) MERGE (s)-[:RESOLVESTO {predicate:'resolvesTo'}]->(t);
MATCH (s:KGClass {id:'citation'}), (t:KGClass {id:'recommendation'}) MERGE (s)-[:RESOLVESTO {predicate:'resolvesTo'}]->(t);
MATCH (s:KGClass {id:'citation'}), (t:KGClass {id:'schedule'}) MERGE (s)-[:RESOLVESTO {predicate:'resolvesTo'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'schedule-entry'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'indicator'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'health-intervention'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);

// WHO SMART Guidelines knowledge graph -- L2 ONTOLOGY (type graph).
// Generated by tools/build-exports.mjs. Do not edit; edit the ontology JSON.
//
// These are CLASSES and LICENSED EDGES, not DAK instance data. Loading this gives you the
// schema to explore; a DAK's own graph is generated by that DAK's IG build. See docs/STORAGE.md.
//
// Every statement is MERGE, so re-running is safe.
//
// RUN THIS AGAINST A USER DATABASE, NOT `system`. The CREATE CONSTRAINT below is rejected
// with "can only be executed in a user database" if `system` is selected, which is where
// Neo4j Browser can land you after connecting. Switch first:
//
//     :use neo4j                                    (Browser, or your database's name)
//     cypher-shell -d neo4j -f <this file>           (shell)
//
// REQUIRES l1.cypher TO BE LOADED FIRST.
// This layer licenses edges onto imported classes (external-artifact, health-intervention, indicator, recommendation, schedule, schedule-entry, terminology-code). The MATCH
// statements below find nothing if those classes are absent, and Cypher does not treat
// that as an error -- the edges would simply be missing. Verify with the query at the
// end of this file.

MERGE (:KGClass:Kit {id:'dak', name:'Digital Adaptation Kit', kind:'Kit', layer:'l2', iri:'http://smart.who.int/kg/dak'});
MERGE (:KGClass:Component {id:'persona', name:'Generic Persona', kind:'Component', layer:'l2', iri:'http://smart.who.int/kg/persona'});
MERGE (:KGClass:Component {id:'user-scenario', name:'User Scenario', kind:'Component', layer:'l2', iri:'http://smart.who.int/kg/user-scenario'});
MERGE (:KGClass:Component {id:'business-process', name:'Business Process Workflow', kind:'Component', layer:'l2', iri:'http://smart.who.int/kg/business-process'});
MERGE (:KGClass:Element {id:'dak-task', name:'Task Entry', kind:'Element', layer:'l2', iri:'http://smart.who.int/kg/dak-task'});
MERGE (:KGClass:Component {id:'data-element', name:'Core Data Element', kind:'Component', layer:'l2', iri:'http://smart.who.int/kg/data-element'});
MERGE (:KGClass:Component {id:'decision-support-logic', name:'Decision-Support Logic', kind:'Component', layer:'l2', iri:'http://smart.who.int/kg/decision-support-logic'});
MERGE (:KGClass:Component {id:'scheduling-logic', name:'Scheduling Logic', kind:'Component', layer:'l2', iri:'http://smart.who.int/kg/scheduling-logic'});
MERGE (:KGClass:Component {id:'program-indicator', name:'Program Indicator', kind:'Component', layer:'l2', iri:'http://smart.who.int/kg/program-indicator'});
MERGE (:KGClass:Component {id:'functional-requirement', name:'Functional Requirement', kind:'Component', layer:'l2', iri:'http://smart.who.int/kg/functional-requirement'});
MERGE (:KGClass:Component {id:'non-functional-requirement', name:'Non-Functional Requirement', kind:'Component', layer:'l2', iri:'http://smart.who.int/kg/non-functional-requirement'});
MERGE (:KGClass:Element {id:'requirement-statement', name:'Requirement Statement', kind:'Element', layer:'l2', iri:'http://smart.who.int/kg/requirement-statement'});
MERGE (:KGClass:Component {id:'test-scenario', name:'Test Scenario', kind:'Component', layer:'l2', iri:'http://smart.who.int/kg/test-scenario'});

MATCH (s:KGClass {id:'dak'}), (t:KGClass {id:'health-intervention'}) MERGE (s)-[:HASCOMPONENT {predicate:'hasComponent', qualifier:'healthInterventions'}]->(t);
MATCH (s:KGClass {id:'dak'}), (t:KGClass {id:'persona'}) MERGE (s)-[:HASCOMPONENT {predicate:'hasComponent', qualifier:'personas'}]->(t);
MATCH (s:KGClass {id:'dak'}), (t:KGClass {id:'user-scenario'}) MERGE (s)-[:HASCOMPONENT {predicate:'hasComponent', qualifier:'userScenarios'}]->(t);
MATCH (s:KGClass {id:'dak'}), (t:KGClass {id:'business-process'}) MERGE (s)-[:HASCOMPONENT {predicate:'hasComponent', qualifier:'businessProcesses'}]->(t);
MATCH (s:KGClass {id:'dak'}), (t:KGClass {id:'data-element'}) MERGE (s)-[:HASCOMPONENT {predicate:'hasComponent', qualifier:'dataElements'}]->(t);
MATCH (s:KGClass {id:'dak'}), (t:KGClass {id:'decision-support-logic'}) MERGE (s)-[:HASCOMPONENT {predicate:'hasComponent', qualifier:'decisionLogic'}]->(t);
MATCH (s:KGClass {id:'dak'}), (t:KGClass {id:'program-indicator'}) MERGE (s)-[:HASCOMPONENT {predicate:'hasComponent', qualifier:'indicators'}]->(t);
MATCH (s:KGClass {id:'dak'}), (t:KGClass {id:'functional-requirement'}) MERGE (s)-[:HASCOMPONENT {predicate:'hasComponent', qualifier:'requirements'}]->(t);
MATCH (s:KGClass {id:'dak'}), (t:KGClass {id:'non-functional-requirement'}) MERGE (s)-[:HASCOMPONENT {predicate:'hasComponent', qualifier:'requirements'}]->(t);
MATCH (s:KGClass {id:'dak'}), (t:KGClass {id:'test-scenario'}) MERGE (s)-[:HASCOMPONENT {predicate:'hasComponent', qualifier:'testScenarios'}]->(t);
MATCH (s:KGClass {id:'dak'}), (t:KGClass {id:'scheduling-logic'}) MERGE (s)-[:HASCOMPONENT {predicate:'hasComponent', qualifier:'schedulingLogic'}]->(t);
MATCH (s:KGClass {id:'scheduling-logic'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:SOURCEDFROM {predicate:'sourcedFrom'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'business-process'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'decision-support-logic'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'persona'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'user-scenario'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'indicator'}), (t:KGClass {id:'program-indicator'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'schedule-entry'}), (t:KGClass {id:'scheduling-logic'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'schedule'}), (t:KGClass {id:'scheduling-logic'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'business-process'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:SOURCEDFROM {predicate:'sourcedFrom'}]->(t);
MATCH (s:KGClass {id:'decision-support-logic'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:SOURCEDFROM {predicate:'sourcedFrom'}]->(t);
MATCH (s:KGClass {id:'test-scenario'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:SOURCEDFROM {predicate:'sourcedFrom'}]->(t);
MATCH (s:KGClass {id:'data-element'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:SOURCEDFROM {predicate:'sourcedFrom'}]->(t);
MATCH (s:KGClass {id:'persona'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:SOURCEDFROM {predicate:'sourcedFrom'}]->(t);
MATCH (s:KGClass {id:'user-scenario'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:SOURCEDFROM {predicate:'sourcedFrom'}]->(t);
MATCH (s:KGClass {id:'program-indicator'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:SOURCEDFROM {predicate:'sourcedFrom'}]->(t);
MATCH (s:KGClass {id:'functional-requirement'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:SOURCEDFROM {predicate:'sourcedFrom'}]->(t);
MATCH (s:KGClass {id:'non-functional-requirement'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:SOURCEDFROM {predicate:'sourcedFrom'}]->(t);
MATCH (s:KGClass {id:'business-process'}), (t:KGClass {id:'user-scenario'}) MERGE (s)-[:REALISES {predicate:'realises'}]->(t);
MATCH (s:KGClass {id:'user-scenario'}), (t:KGClass {id:'persona'}) MERGE (s)-[:INVOLVES {predicate:'involves'}]->(t);
MATCH (s:KGClass {id:'functional-requirement'}), (t:KGClass {id:'persona'}) MERGE (s)-[:FULFILLEDBY {predicate:'fulfilledBy'}]->(t);
MATCH (s:KGClass {id:'functional-requirement'}), (t:KGClass {id:'requirement-statement'}) MERGE (s)-[:HASSTATEMENT {predicate:'hasStatement'}]->(t);
MATCH (s:KGClass {id:'non-functional-requirement'}), (t:KGClass {id:'requirement-statement'}) MERGE (s)-[:HASSTATEMENT {predicate:'hasStatement'}]->(t);
MATCH (s:KGClass {id:'business-process'}), (t:KGClass {id:'dak-task'}) MERGE (s)-[:LISTSTASK {predicate:'listsTask'}]->(t);
MATCH (s:KGClass {id:'program-indicator'}), (t:KGClass {id:'health-intervention'}) MERGE (s)-[:REFERENCES {predicate:'references'}]->(t);
MATCH (s:KGClass {id:'program-indicator'}), (t:KGClass {id:'indicator'}) MERGE (s)-[:DERIVEDFROM {predicate:'derivedFrom'}]->(t);
MATCH (s:KGClass {id:'persona'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'data-element'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'program-indicator'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'functional-requirement'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'non-functional-requirement'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'functional-requirement'}), (t:KGClass {id:'recommendation'}) MERGE (s)-[:DERIVEDFROM {predicate:'derivedFrom'}]->(t);
MATCH (s:KGClass {id:'non-functional-requirement'}), (t:KGClass {id:'recommendation'}) MERGE (s)-[:DERIVEDFROM {predicate:'derivedFrom'}]->(t);
MATCH (s:KGClass {id:'requirement-statement'}), (t:KGClass {id:'test-scenario'}) MERGE (s)-[:VERIFIEDBY {predicate:'verifiedBy'}]->(t);

// Verification. Must return 7 rows -- one per imported class this layer
// builds on. Fewer means an imported layer was not loaded and edges above are missing.
// MATCH (c:KGClass) WHERE c.id IN ['external-artifact', 'health-intervention', 'indicator', 'recommendation', 'schedule', 'schedule-entry', 'terminology-code'] RETURN c.id;

// WHO SMART Guidelines knowledge graph -- L2-BPMN ONTOLOGY (type graph).
// Generated by tools/build-exports.mjs. Do not edit; edit the ontology JSON.
//
// These are CLASSES and LICENSED EDGES, not DAK instance data. Loading this gives you the
// schema to explore; a DAK's own graph is generated by that DAK's IG build. See docs/STORAGE.md.
//
// Every statement is MERGE, so re-running is safe.
//
// RUN THIS AGAINST A USER DATABASE, NOT `system`. The CREATE CONSTRAINT below is rejected
// with "can only be executed in a user database" if `system` is selected, which is where
// Neo4j Browser can land you after connecting. Switch first:
//
//     :use neo4j                                    (Browser, or your database's name)
//     cypher-shell -d neo4j -f <this file>           (shell)
//
// REQUIRES l2.cypher and l1.cypher TO BE LOADED FIRST.
// This layer licenses edges onto imported classes (business-process, dak-task, persona). The MATCH
// statements below find nothing if those classes are absent, and Cypher does not treat
// that as an error -- the edges would simply be missing. Verify with the query at the
// end of this file.

MERGE (:KGClass:Artefact {id:'bpmn-definitions', name:'BPMN File', kind:'Artefact', layer:'l2-bpmn', iri:'http://smart.who.int/kg/bpmn-definitions'});
MERGE (:KGClass:Structure {id:'bpmn-process', name:'BPMN Process', kind:'Structure', layer:'l2-bpmn', iri:'http://smart.who.int/kg/bpmn-process'});
MERGE (:KGClass:Structure {id:'bpmn-participant', name:'BPMN Participant', kind:'Structure', layer:'l2-bpmn', iri:'http://smart.who.int/kg/bpmn-participant'});
MERGE (:KGClass:Structure {id:'bpmn-task', name:'BPMN Task', kind:'Structure', layer:'l2-bpmn', iri:'http://smart.who.int/kg/bpmn-task'});
MERGE (:KGClass:Structure {id:'bpmn-gateway', name:'BPMN Gateway', kind:'Structure', layer:'l2-bpmn', iri:'http://smart.who.int/kg/bpmn-gateway'});
MERGE (:KGClass:Structure {id:'bpmn-event', name:'BPMN Event', kind:'Structure', layer:'l2-bpmn', iri:'http://smart.who.int/kg/bpmn-event'});

MATCH (s:KGClass {id:'bpmn-definitions'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:ELABORATES {predicate:'elaborates', note:'One artefact, one IRI: instances of these two classes are the same node, described at two layers.'}]->(t);

MATCH (s:KGClass {id:'bpmn-definitions'}), (t:KGClass {id:'bpmn-process'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'bpmn-definitions'}), (t:KGClass {id:'bpmn-participant'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'bpmn-process'}), (t:KGClass {id:'bpmn-task'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'bpmn-process'}), (t:KGClass {id:'bpmn-gateway'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'bpmn-process'}), (t:KGClass {id:'bpmn-event'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'bpmn-task'}), (t:KGClass {id:'bpmn-task'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'bpmn-event'}), (t:KGClass {id:'bpmn-task'}) MERGE (s)-[:FLOWSTO {predicate:'flowsTo'}]->(t);
MATCH (s:KGClass {id:'bpmn-event'}), (t:KGClass {id:'bpmn-gateway'}) MERGE (s)-[:FLOWSTO {predicate:'flowsTo'}]->(t);
MATCH (s:KGClass {id:'bpmn-task'}), (t:KGClass {id:'bpmn-task'}) MERGE (s)-[:FLOWSTO {predicate:'flowsTo'}]->(t);
MATCH (s:KGClass {id:'bpmn-task'}), (t:KGClass {id:'bpmn-gateway'}) MERGE (s)-[:FLOWSTO {predicate:'flowsTo'}]->(t);
MATCH (s:KGClass {id:'bpmn-task'}), (t:KGClass {id:'bpmn-event'}) MERGE (s)-[:FLOWSTO {predicate:'flowsTo'}]->(t);
MATCH (s:KGClass {id:'bpmn-gateway'}), (t:KGClass {id:'bpmn-task'}) MERGE (s)-[:FLOWSTO {predicate:'flowsTo'}]->(t);
MATCH (s:KGClass {id:'bpmn-gateway'}), (t:KGClass {id:'bpmn-gateway'}) MERGE (s)-[:FLOWSTO {predicate:'flowsTo'}]->(t);
MATCH (s:KGClass {id:'bpmn-gateway'}), (t:KGClass {id:'bpmn-event'}) MERGE (s)-[:FLOWSTO {predicate:'flowsTo'}]->(t);
MATCH (s:KGClass {id:'bpmn-task'}), (t:KGClass {id:'bpmn-task'}) MERGE (s)-[:MESSAGETO {predicate:'messageTo'}]->(t);
MATCH (s:KGClass {id:'bpmn-task'}), (t:KGClass {id:'bpmn-event'}) MERGE (s)-[:MESSAGETO {predicate:'messageTo'}]->(t);
MATCH (s:KGClass {id:'bpmn-event'}), (t:KGClass {id:'bpmn-task'}) MERGE (s)-[:MESSAGETO {predicate:'messageTo'}]->(t);
MATCH (s:KGClass {id:'bpmn-participant'}), (t:KGClass {id:'persona'}) MERGE (s)-[:PERFORMEDBY {predicate:'performedBy'}]->(t);
MATCH (s:KGClass {id:'dak-task'}), (t:KGClass {id:'bpmn-task'}) MERGE (s)-[:DESCRIBES {predicate:'describes'}]->(t);
MATCH (s:KGClass {id:'business-process'}), (t:KGClass {id:'bpmn-definitions'}) MERGE (s)-[:SOURCEDFROM {predicate:'sourcedFrom'}]->(t);

// Verification. Must return 3 rows -- one per imported class this layer
// builds on. Fewer means an imported layer was not loaded and edges above are missing.
// MATCH (c:KGClass) WHERE c.id IN ['business-process', 'dak-task', 'persona'] RETURN c.id;

// WHO SMART Guidelines knowledge graph -- L2-DMN ONTOLOGY (type graph).
// Generated by tools/build-exports.mjs. Do not edit; edit the ontology JSON.
//
// These are CLASSES and LICENSED EDGES, not DAK instance data. Loading this gives you the
// schema to explore; a DAK's own graph is generated by that DAK's IG build. See docs/STORAGE.md.
//
// Every statement is MERGE, so re-running is safe.
//
// RUN THIS AGAINST A USER DATABASE, NOT `system`. The CREATE CONSTRAINT below is rejected
// with "can only be executed in a user database" if `system` is selected, which is where
// Neo4j Browser can land you after connecting. Switch first:
//
//     :use neo4j                                    (Browser, or your database's name)
//     cypher-shell -d neo4j -f <this file>           (shell)
//
// REQUIRES l2-bpmn.cypher and l2.cypher and l1.cypher TO BE LOADED FIRST.
// This layer licenses edges onto imported classes (bpmn-task, citation, data-element, decision-support-logic, external-artifact). The MATCH
// statements below find nothing if those classes are absent, and Cypher does not treat
// that as an error -- the edges would simply be missing. Verify with the query at the
// end of this file.

MERGE (:KGClass:Artefact {id:'dmn-definitions', name:'DMN File', kind:'Artefact', layer:'l2-dmn', iri:'http://smart.who.int/kg/dmn-definitions'});
MERGE (:KGClass:Structure {id:'dmn-decision', name:'DMN Decision', kind:'Structure', layer:'l2-dmn', iri:'http://smart.who.int/kg/dmn-decision'});
MERGE (:KGClass:Structure {id:'dmn-decision-table', name:'DMN Decision Table', kind:'Structure', layer:'l2-dmn', iri:'http://smart.who.int/kg/dmn-decision-table'});
MERGE (:KGClass:Structure {id:'dmn-input-clause', name:'DMN Input Clause', kind:'Structure', layer:'l2-dmn', iri:'http://smart.who.int/kg/dmn-input-clause'});
MERGE (:KGClass:Structure {id:'dmn-output-clause', name:'DMN Output Clause', kind:'Structure', layer:'l2-dmn', iri:'http://smart.who.int/kg/dmn-output-clause'});
MERGE (:KGClass:Structure {id:'dmn-rule', name:'DMN Rule', kind:'Structure', layer:'l2-dmn', iri:'http://smart.who.int/kg/dmn-rule'});

MATCH (s:KGClass {id:'dmn-definitions'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:ELABORATES {predicate:'elaborates', note:'One artefact, one IRI: instances of these two classes are the same node, described at two layers.'}]->(t);

MATCH (s:KGClass {id:'dmn-definitions'}), (t:KGClass {id:'dmn-decision'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'dmn-decision'}), (t:KGClass {id:'dmn-decision-table'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'dmn-decision-table'}), (t:KGClass {id:'dmn-input-clause'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'dmn-decision-table'}), (t:KGClass {id:'dmn-output-clause'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'dmn-decision-table'}), (t:KGClass {id:'dmn-rule'}) MERGE (s)-[:CONTAINS {predicate:'contains'}]->(t);
MATCH (s:KGClass {id:'dmn-decision'}), (t:KGClass {id:'bpmn-task'}) MERGE (s)-[:INVOKEDBY {predicate:'invokedBy'}]->(t);
MATCH (s:KGClass {id:'dmn-decision'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:INVOKEDBY {predicate:'invokedBy'}]->(t);
MATCH (s:KGClass {id:'dmn-input-clause'}), (t:KGClass {id:'data-element'}) MERGE (s)-[:READS {predicate:'reads'}]->(t);
MATCH (s:KGClass {id:'dmn-rule'}), (t:KGClass {id:'citation'}) MERGE (s)-[:CITESSOURCE {predicate:'citesSource'}]->(t);
MATCH (s:KGClass {id:'decision-support-logic'}), (t:KGClass {id:'dmn-definitions'}) MERGE (s)-[:SOURCEDFROM {predicate:'sourcedFrom'}]->(t);

// Verification. Must return 5 rows -- one per imported class this layer
// builds on. Fewer means an imported layer was not loaded and edges above are missing.
// MATCH (c:KGClass) WHERE c.id IN ['bpmn-task', 'citation', 'data-element', 'decision-support-logic', 'external-artifact'] RETURN c.id;

// WHO SMART Guidelines knowledge graph -- L3 ONTOLOGY (type graph).
// Generated by tools/build-exports.mjs. Do not edit; edit the ontology JSON.
//
// These are CLASSES and LICENSED EDGES, not DAK instance data. Loading this gives you the
// schema to explore; a DAK's own graph is generated by that DAK's IG build. See docs/STORAGE.md.
//
// Every statement is MERGE, so re-running is safe.
//
// RUN THIS AGAINST A USER DATABASE, NOT `system`. The CREATE CONSTRAINT below is rejected
// with "can only be executed in a user database" if `system` is selected, which is where
// Neo4j Browser can land you after connecting. Switch first:
//
//     :use neo4j                                    (Browser, or your database's name)
//     cypher-shell -d neo4j -f <this file>           (shell)
//
// REQUIRES l2-dmn.cypher and l2-bpmn.cypher and l2.cypher and l1.cypher TO BE LOADED FIRST.
// This layer licenses edges onto imported classes (bpmn-process, bpmn-task, business-process, citation, data-element, decision-support-logic, dmn-decision, functional-requirement, non-functional-requirement, persona, program-indicator, scheduling-logic, terminology-code). The MATCH
// statements below find nothing if those classes are absent, and Cypher does not treat
// that as an error -- the edges would simply be missing. Verify with the query at the
// end of this file.

MERGE (:KGClass:Knowledge {id:'plan-definition', name:'Plan Definition', kind:'Knowledge', layer:'l3', iri:'http://smart.who.int/kg/plan-definition'});
MERGE (:KGClass:Knowledge {id:'activity-definition', name:'Activity Definition', kind:'Knowledge', layer:'l3', iri:'http://smart.who.int/kg/activity-definition'});
MERGE (:KGClass:Knowledge {id:'library', name:'Library', kind:'Knowledge', layer:'l3', iri:'http://smart.who.int/kg/library'});
MERGE (:KGClass:Knowledge {id:'cql-library', name:'CQL File', kind:'Knowledge', layer:'l3', iri:'http://smart.who.int/kg/cql-library'});
MERGE (:KGClass:Knowledge {id:'measure', name:'Measure', kind:'Knowledge', layer:'l3', iri:'http://smart.who.int/kg/measure'});
MERGE (:KGClass:Knowledge {id:'questionnaire', name:'Questionnaire', kind:'Knowledge', layer:'l3', iri:'http://smart.who.int/kg/questionnaire'});
MERGE (:KGClass:Conformance {id:'structure-map', name:'Structure Map', kind:'Conformance', layer:'l3', iri:'http://smart.who.int/kg/structure-map'});
MERGE (:KGClass:Conformance {id:'structure-definition', name:'Logical Model', kind:'Conformance', layer:'l3', iri:'http://smart.who.int/kg/structure-definition'});
MERGE (:KGClass:Conformance {id:'profile', name:'Profile', kind:'Conformance', layer:'l3', iri:'http://smart.who.int/kg/profile'});
MERGE (:KGClass:Conformance {id:'value-set', name:'Value Set', kind:'Conformance', layer:'l3', iri:'http://smart.who.int/kg/value-set'});
MERGE (:KGClass:Conformance {id:'code-system', name:'Code System', kind:'Conformance', layer:'l3', iri:'http://smart.who.int/kg/code-system'});
MERGE (:KGClass:Conformance {id:'concept-map', name:'Concept Map', kind:'Conformance', layer:'l3', iri:'http://smart.who.int/kg/concept-map'});
MERGE (:KGClass:Conformance {id:'actor-definition', name:'Actor Definition', kind:'Conformance', layer:'l3', iri:'http://smart.who.int/kg/actor-definition'});
MERGE (:KGClass:Conformance {id:'requirements', name:'Requirements', kind:'Conformance', layer:'l3', iri:'http://smart.who.int/kg/requirements'});

MATCH (s:KGClass {id:'plan-definition'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:ELABORATES {predicate:'elaborates', note:'One artefact, one IRI: instances of these two classes are the same node, described at two layers.'}]->(t);

MATCH (s:KGClass {id:'activity-definition'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:ELABORATES {predicate:'elaborates', note:'One artefact, one IRI: instances of these two classes are the same node, described at two layers.'}]->(t);

MATCH (s:KGClass {id:'library'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:ELABORATES {predicate:'elaborates', note:'One artefact, one IRI: instances of these two classes are the same node, described at two layers.'}]->(t);

MATCH (s:KGClass {id:'measure'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:ELABORATES {predicate:'elaborates', note:'One artefact, one IRI: instances of these two classes are the same node, described at two layers.'}]->(t);

MATCH (s:KGClass {id:'questionnaire'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:ELABORATES {predicate:'elaborates', note:'One artefact, one IRI: instances of these two classes are the same node, described at two layers.'}]->(t);

MATCH (s:KGClass {id:'structure-map'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:ELABORATES {predicate:'elaborates', note:'One artefact, one IRI: instances of these two classes are the same node, described at two layers.'}]->(t);

MATCH (s:KGClass {id:'structure-definition'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:ELABORATES {predicate:'elaborates', note:'One artefact, one IRI: instances of these two classes are the same node, described at two layers.'}]->(t);

MATCH (s:KGClass {id:'profile'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:ELABORATES {predicate:'elaborates', note:'One artefact, one IRI: instances of these two classes are the same node, described at two layers.'}]->(t);

MATCH (s:KGClass {id:'value-set'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:ELABORATES {predicate:'elaborates', note:'One artefact, one IRI: instances of these two classes are the same node, described at two layers.'}]->(t);

MATCH (s:KGClass {id:'code-system'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:ELABORATES {predicate:'elaborates', note:'One artefact, one IRI: instances of these two classes are the same node, described at two layers.'}]->(t);

MATCH (s:KGClass {id:'concept-map'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:ELABORATES {predicate:'elaborates', note:'One artefact, one IRI: instances of these two classes are the same node, described at two layers.'}]->(t);

MATCH (s:KGClass {id:'actor-definition'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:ELABORATES {predicate:'elaborates', note:'One artefact, one IRI: instances of these two classes are the same node, described at two layers.'}]->(t);

MATCH (s:KGClass {id:'requirements'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:ELABORATES {predicate:'elaborates', note:'One artefact, one IRI: instances of these two classes are the same node, described at two layers.'}]->(t);

MATCH (s:KGClass {id:'business-process'}), (t:KGClass {id:'plan-definition'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'business-process'}), (t:KGClass {id:'activity-definition'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'bpmn-process'}), (t:KGClass {id:'plan-definition'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'bpmn-task'}), (t:KGClass {id:'activity-definition'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'decision-support-logic'}), (t:KGClass {id:'plan-definition'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'decision-support-logic'}), (t:KGClass {id:'activity-definition'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'decision-support-logic'}), (t:KGClass {id:'library'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'decision-support-logic'}), (t:KGClass {id:'cql-library'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'dmn-decision'}), (t:KGClass {id:'plan-definition'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'scheduling-logic'}), (t:KGClass {id:'plan-definition'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'scheduling-logic'}), (t:KGClass {id:'cql-library'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'persona'}), (t:KGClass {id:'actor-definition'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'program-indicator'}), (t:KGClass {id:'measure'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'program-indicator'}), (t:KGClass {id:'cql-library'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'data-element'}), (t:KGClass {id:'structure-definition'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'data-element'}), (t:KGClass {id:'questionnaire'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'data-element'}), (t:KGClass {id:'structure-map'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'data-element'}), (t:KGClass {id:'value-set'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'data-element'}), (t:KGClass {id:'code-system'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'data-element'}), (t:KGClass {id:'profile'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'data-element'}), (t:KGClass {id:'concept-map'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'data-element'}), (t:KGClass {id:'cql-library'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'functional-requirement'}), (t:KGClass {id:'requirements'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'non-functional-requirement'}), (t:KGClass {id:'requirements'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'plan-definition'}), (t:KGClass {id:'library'}) MERGE (s)-[:USES {predicate:'uses'}]->(t);
MATCH (s:KGClass {id:'plan-definition'}), (t:KGClass {id:'activity-definition'}) MERGE (s)-[:USES {predicate:'uses'}]->(t);
MATCH (s:KGClass {id:'measure'}), (t:KGClass {id:'library'}) MERGE (s)-[:USES {predicate:'uses'}]->(t);
MATCH (s:KGClass {id:'library'}), (t:KGClass {id:'cql-library'}) MERGE (s)-[:USES {predicate:'uses'}]->(t);
MATCH (s:KGClass {id:'questionnaire'}), (t:KGClass {id:'structure-map'}) MERGE (s)-[:USES {predicate:'uses'}]->(t);
MATCH (s:KGClass {id:'questionnaire'}), (t:KGClass {id:'structure-definition'}) MERGE (s)-[:USES {predicate:'uses'}]->(t);
MATCH (s:KGClass {id:'structure-map'}), (t:KGClass {id:'structure-definition'}) MERGE (s)-[:USES {predicate:'uses'}]->(t);
MATCH (s:KGClass {id:'profile'}), (t:KGClass {id:'structure-definition'}) MERGE (s)-[:USES {predicate:'uses'}]->(t);
MATCH (s:KGClass {id:'value-set'}), (t:KGClass {id:'code-system'}) MERGE (s)-[:USES {predicate:'uses'}]->(t);
MATCH (s:KGClass {id:'concept-map'}), (t:KGClass {id:'code-system'}) MERGE (s)-[:USES {predicate:'uses'}]->(t);
MATCH (s:KGClass {id:'plan-definition'}), (t:KGClass {id:'citation'}) MERGE (s)-[:CITESSOURCE {predicate:'citesSource'}]->(t);
MATCH (s:KGClass {id:'library'}), (t:KGClass {id:'citation'}) MERGE (s)-[:CITESSOURCE {predicate:'citesSource'}]->(t);
MATCH (s:KGClass {id:'measure'}), (t:KGClass {id:'citation'}) MERGE (s)-[:CITESSOURCE {predicate:'citesSource'}]->(t);
MATCH (s:KGClass {id:'structure-definition'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'measure'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);

// Verification. Must return 13 rows -- one per imported class this layer
// builds on. Fewer means an imported layer was not loaded and edges above are missing.
// MATCH (c:KGClass) WHERE c.id IN ['bpmn-process', 'bpmn-task', 'business-process', 'citation', 'data-element', 'decision-support-logic', 'dmn-decision', 'functional-requirement', 'non-functional-requirement', 'persona', 'program-indicator', 'scheduling-logic', 'terminology-code'] RETURN c.id;
