// WHO SMART Guidelines knowledge graph -- L2 ONTOLOGY (type graph).
// Generated by tools/build-exports.mjs. Do not edit; edit the ontology JSON.
//
// These are CLASSES and LICENSED EDGES, not DAK instance data. Loading this gives you the
// schema to explore; a DAK's own graph is generated by that DAK's IG build. See docs/STORAGE.md.
//
// Every statement is MERGE, so re-running is safe.
//
// RUN THIS AGAINST A USER DATABASE, NOT `system`. The CREATE CONSTRAINT below is rejected
// with "can only be executed in a user database" if `system` is selected, which is where
// Neo4j Browser can land you after connecting. Switch first:
//
//     :use neo4j                                    (Browser, or your database's name)
//     cypher-shell -d neo4j -f <this file>           (shell)
//
// REQUIRES l1.cypher TO BE LOADED FIRST.
// This layer licenses edges onto imported classes (external-artifact, health-intervention, indicator, recommendation, schedule, schedule-entry, terminology-code). The MATCH
// statements below find nothing if those classes are absent, and Cypher does not treat
// that as an error -- the edges would simply be missing. Verify with the query at the
// end of this file.

CREATE CONSTRAINT kgclass_id IF NOT EXISTS
FOR (c:KGClass) REQUIRE c.id IS UNIQUE;

MERGE (:KGClass:Kit {id:'dak', name:'Digital Adaptation Kit', kind:'Kit', layer:'l2', iri:'http://smart.who.int/kg/dak'});
MERGE (:KGClass:Component {id:'persona', name:'Generic Persona', kind:'Component', layer:'l2', iri:'http://smart.who.int/kg/persona'});
MERGE (:KGClass:Component {id:'user-scenario', name:'User Scenario', kind:'Component', layer:'l2', iri:'http://smart.who.int/kg/user-scenario'});
MERGE (:KGClass:Component {id:'business-process', name:'Business Process Workflow', kind:'Component', layer:'l2', iri:'http://smart.who.int/kg/business-process'});
MERGE (:KGClass:Element {id:'dak-task', name:'Task Entry', kind:'Element', layer:'l2', iri:'http://smart.who.int/kg/dak-task'});
MERGE (:KGClass:Component {id:'data-element', name:'Core Data Element', kind:'Component', layer:'l2', iri:'http://smart.who.int/kg/data-element'});
MERGE (:KGClass:Component {id:'decision-support-logic', name:'Decision-Support Logic', kind:'Component', layer:'l2', iri:'http://smart.who.int/kg/decision-support-logic'});
MERGE (:KGClass:Component {id:'scheduling-logic', name:'Scheduling Logic', kind:'Component', layer:'l2', iri:'http://smart.who.int/kg/scheduling-logic'});
MERGE (:KGClass:Component {id:'program-indicator', name:'Program Indicator', kind:'Component', layer:'l2', iri:'http://smart.who.int/kg/program-indicator'});
MERGE (:KGClass:Component {id:'functional-requirement', name:'Functional Requirement', kind:'Component', layer:'l2', iri:'http://smart.who.int/kg/functional-requirement'});
MERGE (:KGClass:Component {id:'non-functional-requirement', name:'Non-Functional Requirement', kind:'Component', layer:'l2', iri:'http://smart.who.int/kg/non-functional-requirement'});
MERGE (:KGClass:Element {id:'requirement-statement', name:'Requirement Statement', kind:'Element', layer:'l2', iri:'http://smart.who.int/kg/requirement-statement'});
MERGE (:KGClass:Component {id:'test-scenario', name:'Test Scenario', kind:'Component', layer:'l2', iri:'http://smart.who.int/kg/test-scenario'});

MATCH (s:KGClass {id:'dak'}), (t:KGClass {id:'health-intervention'}) MERGE (s)-[:HASCOMPONENT {predicate:'hasComponent', qualifier:'healthInterventions'}]->(t);
MATCH (s:KGClass {id:'dak'}), (t:KGClass {id:'persona'}) MERGE (s)-[:HASCOMPONENT {predicate:'hasComponent', qualifier:'personas'}]->(t);
MATCH (s:KGClass {id:'dak'}), (t:KGClass {id:'user-scenario'}) MERGE (s)-[:HASCOMPONENT {predicate:'hasComponent', qualifier:'userScenarios'}]->(t);
MATCH (s:KGClass {id:'dak'}), (t:KGClass {id:'business-process'}) MERGE (s)-[:HASCOMPONENT {predicate:'hasComponent', qualifier:'businessProcesses'}]->(t);
MATCH (s:KGClass {id:'dak'}), (t:KGClass {id:'data-element'}) MERGE (s)-[:HASCOMPONENT {predicate:'hasComponent', qualifier:'dataElements'}]->(t);
MATCH (s:KGClass {id:'dak'}), (t:KGClass {id:'decision-support-logic'}) MERGE (s)-[:HASCOMPONENT {predicate:'hasComponent', qualifier:'decisionLogic'}]->(t);
MATCH (s:KGClass {id:'dak'}), (t:KGClass {id:'program-indicator'}) MERGE (s)-[:HASCOMPONENT {predicate:'hasComponent', qualifier:'indicators'}]->(t);
MATCH (s:KGClass {id:'dak'}), (t:KGClass {id:'functional-requirement'}) MERGE (s)-[:HASCOMPONENT {predicate:'hasComponent', qualifier:'requirements'}]->(t);
MATCH (s:KGClass {id:'dak'}), (t:KGClass {id:'non-functional-requirement'}) MERGE (s)-[:HASCOMPONENT {predicate:'hasComponent', qualifier:'requirements'}]->(t);
MATCH (s:KGClass {id:'dak'}), (t:KGClass {id:'test-scenario'}) MERGE (s)-[:HASCOMPONENT {predicate:'hasComponent', qualifier:'testScenarios'}]->(t);
MATCH (s:KGClass {id:'dak'}), (t:KGClass {id:'scheduling-logic'}) MERGE (s)-[:HASCOMPONENT {predicate:'hasComponent', qualifier:'schedulingLogic'}]->(t);
MATCH (s:KGClass {id:'scheduling-logic'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:SOURCEDFROM {predicate:'sourcedFrom'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'business-process'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'decision-support-logic'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'persona'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'recommendation'}), (t:KGClass {id:'user-scenario'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'indicator'}), (t:KGClass {id:'program-indicator'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'schedule-entry'}), (t:KGClass {id:'scheduling-logic'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'schedule'}), (t:KGClass {id:'scheduling-logic'}) MERGE (s)-[:IMPLEMENTEDBY {predicate:'implementedBy'}]->(t);
MATCH (s:KGClass {id:'business-process'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:SOURCEDFROM {predicate:'sourcedFrom'}]->(t);
MATCH (s:KGClass {id:'decision-support-logic'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:SOURCEDFROM {predicate:'sourcedFrom'}]->(t);
MATCH (s:KGClass {id:'test-scenario'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:SOURCEDFROM {predicate:'sourcedFrom'}]->(t);
MATCH (s:KGClass {id:'data-element'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:SOURCEDFROM {predicate:'sourcedFrom'}]->(t);
MATCH (s:KGClass {id:'persona'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:SOURCEDFROM {predicate:'sourcedFrom'}]->(t);
MATCH (s:KGClass {id:'user-scenario'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:SOURCEDFROM {predicate:'sourcedFrom'}]->(t);
MATCH (s:KGClass {id:'program-indicator'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:SOURCEDFROM {predicate:'sourcedFrom'}]->(t);
MATCH (s:KGClass {id:'functional-requirement'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:SOURCEDFROM {predicate:'sourcedFrom'}]->(t);
MATCH (s:KGClass {id:'non-functional-requirement'}), (t:KGClass {id:'external-artifact'}) MERGE (s)-[:SOURCEDFROM {predicate:'sourcedFrom'}]->(t);
MATCH (s:KGClass {id:'business-process'}), (t:KGClass {id:'user-scenario'}) MERGE (s)-[:REALISES {predicate:'realises'}]->(t);
MATCH (s:KGClass {id:'user-scenario'}), (t:KGClass {id:'persona'}) MERGE (s)-[:INVOLVES {predicate:'involves'}]->(t);
MATCH (s:KGClass {id:'functional-requirement'}), (t:KGClass {id:'persona'}) MERGE (s)-[:FULFILLEDBY {predicate:'fulfilledBy'}]->(t);
MATCH (s:KGClass {id:'functional-requirement'}), (t:KGClass {id:'requirement-statement'}) MERGE (s)-[:HASSTATEMENT {predicate:'hasStatement'}]->(t);
MATCH (s:KGClass {id:'non-functional-requirement'}), (t:KGClass {id:'requirement-statement'}) MERGE (s)-[:HASSTATEMENT {predicate:'hasStatement'}]->(t);
MATCH (s:KGClass {id:'business-process'}), (t:KGClass {id:'dak-task'}) MERGE (s)-[:LISTSTASK {predicate:'listsTask'}]->(t);
MATCH (s:KGClass {id:'program-indicator'}), (t:KGClass {id:'health-intervention'}) MERGE (s)-[:REFERENCES {predicate:'references'}]->(t);
MATCH (s:KGClass {id:'program-indicator'}), (t:KGClass {id:'indicator'}) MERGE (s)-[:DERIVEDFROM {predicate:'derivedFrom'}]->(t);
MATCH (s:KGClass {id:'persona'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'data-element'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'program-indicator'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'functional-requirement'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'non-functional-requirement'}), (t:KGClass {id:'terminology-code'}) MERGE (s)-[:CROSSREFERENCES {predicate:'crossReferences'}]->(t);
MATCH (s:KGClass {id:'functional-requirement'}), (t:KGClass {id:'recommendation'}) MERGE (s)-[:DERIVEDFROM {predicate:'derivedFrom'}]->(t);
MATCH (s:KGClass {id:'non-functional-requirement'}), (t:KGClass {id:'recommendation'}) MERGE (s)-[:DERIVEDFROM {predicate:'derivedFrom'}]->(t);
MATCH (s:KGClass {id:'requirement-statement'}), (t:KGClass {id:'test-scenario'}) MERGE (s)-[:VERIFIEDBY {predicate:'verifiedBy'}]->(t);

// Verification. Must return 7 rows -- one per imported class this layer
// builds on. Fewer means an imported layer was not loaded and edges above are missing.
// MATCH (c:KGClass) WHERE c.id IN ['external-artifact', 'health-intervention', 'indicator', 'recommendation', 'schedule', 'schedule-entry', 'terminology-code'] RETURN c.id;
