#!/usr/bin/env node
// Builds ontology/<layer>/<layer>.{cypher,ttl,context.jsonld} from ontology/<layer>/<layer>.json.
//
// One directory per subgraph, each self-contained and named after itself, so a file stays
// identifiable once it has been downloaded and handed to Neo4j or Protege. The .json in each is
// the authored source; the other three are projections and say so in their first line.
//
// Also writes ontology/all.cypher and ontology/all.ttl -- every layer concatenated in dependency
// order, for loading the whole model in one command. Layers license edges onto classes from the
// ones they import, and Cypher does not error on a MATCH that finds nothing, so loading out of
// order silently drops edges. all.cypher removes that footgun.
//
// Both are views of the same model, committed rather than generated on demand because the point of
// a standalone ontology repository is that someone can fetch it in the format their tool reads --
// Turtle into Protege, Cypher into Neo4j -- without installing a toolchain first. `--check` keeps
// them from drifting from ontology.json.
//
// These carry the TYPE graph: classes and licensed edges. They are not DAK data. See docs/STORAGE.md.
//
//   node tools/build-exports.mjs
//   node tools/build-exports.mjs --check

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from "node:fs";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { loadLayer, scopeOf, borrowedClassIds, layerDir, bindingOf } from "./ontology.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
// Which ontology files to export. Each is authored or generated elsewhere; this only projects.
// A layer that imports another is exported on its own: l2.ttl declares L2's classes and references
// L1's through owl:imports, rather than restating them.
const LAYERS = ["l1", "l2", "l2-bpmn", "l2-dmn", "l3"];

const camel = (name) =>
  name.split(/[^A-Za-z0-9]+/).filter(Boolean)
    .map((w) => (/^[A-Z0-9]+$/.test(w) ? w : w[0].toUpperCase() + w.slice(1)))
    .join("");

const cy = (s) => String(s).replace(/\\/g, "\\\\").replace(/'/g, "\\'");
const tt = (s) => String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"');

export function buildCypher(ont, layer = { own: ont, imported: { classes: [], predicates: [], edges: [], layers: [] } }) {
  const borrowed = borrowedClassIds(layer);
  const L = [
    `// WHO SMART Guidelines knowledge graph -- ${(ont.layer ?? "").toUpperCase()} ONTOLOGY (type graph).`,
    "// Generated by tools/build-exports.mjs. Do not edit; edit the ontology JSON.",
    "//",
    "// These are CLASSES and LICENSED EDGES, not DAK instance data. Loading this gives you the",
    "// schema to explore; a DAK's own graph is generated by that DAK's IG build. See docs/STORAGE.md.",
    "//",
    "// Every statement is MERGE, so re-running is safe.",
    "//",
    "// RUN THIS AGAINST A USER DATABASE, NOT `system`. The CREATE CONSTRAINT below is rejected",
    "// with \"can only be executed in a user database\" if `system` is selected, which is where",
    "// Neo4j Browser can land you after connecting. Switch first:",
    "//",
    "//     :use neo4j                                    (Browser, or your database's name)",
    "//     cypher-shell -d neo4j -f <this file>           (shell)",
    ...(borrowed.length
      ? ["//",
         `// REQUIRES ${layer.imported.layers.map((l) => `${l}.cypher`).join(" and ")} TO BE LOADED FIRST.`,
         `// This layer licenses edges onto imported classes (${borrowed.join(", ")}). The MATCH`,
         "// statements below find nothing if those classes are absent, and Cypher does not treat",
         "// that as an error -- the edges would simply be missing. Verify with the query at the",
         "// end of this file."]
      : []),
    "",
    "CREATE CONSTRAINT kgclass_id IF NOT EXISTS",
    "FOR (c:KGClass) REQUIRE c.id IS UNIQUE;",
    "",
  ];
  for (const c of ont.classes) {
    L.push(
      `MERGE (:KGClass:${c.kind} {id:'${cy(c.id)}', name:'${cy(c.name)}', ` +
      `kind:'${c.kind}', layer:'${cy((ont.layer ?? "").toLowerCase())}', iri:'${c.iri}'` +
      (c.archimateType ? `, archimateType:'${c.archimateType}'` : "") + `});`);
  }
  // `elaborates` is a class-level declaration, not a licensed edge -- two classes describing one
  // artefact at different layers, sharing its IRI at instance level. The Turtle carries it as
  // rdfs:subClassOf; without it in Cypher the graph simply stops at external-artifact, and the
  // traversal from a DAK component into the file it names cannot be walked at all.
  const scopeClasses = scopeOf(layer).classes;
  for (const c of ont.classes) {
    if (!c.elaborates || !scopeClasses.has(c.elaborates)) continue;
    L.push("");
    L.push(`MATCH (s:KGClass {id:'${cy(c.id)}'}), (t:KGClass {id:'${cy(c.elaborates)}'}) ` +
           `MERGE (s)-[:ELABORATES {predicate:'elaborates', ` +
           `note:'One artefact, one IRI: instances of these two classes are the same node, ` +
           `described at two layers.'}]->(t);`);
  }

  L.push("");
  for (const e of ont.edges) {
    const props = [`predicate:'${e.predicate}'`];
    if (e.qualifier) props.push(`qualifier:'${cy(e.qualifier)}'`);
    if (e.access) props.push(`access:'${e.access}'`);
    if (e.archimateType) props.push(`archimateType:'${e.archimateType}'`);
    L.push(
      `MATCH (s:KGClass {id:'${e.source}'}), (t:KGClass {id:'${e.target}'}) ` +
      `MERGE (s)-[:${e.predicate.toUpperCase()} {${props.join(", ")}}]->(t);`);
  }
  if (borrowed.length) {
    L.push(
      "",
      `// Verification. Must return ${borrowed.length} rows -- one per imported class this layer`,
      "// builds on. Fewer means an imported layer was not loaded and edges above are missing.",
      `// MATCH (c:KGClass) WHERE c.id IN [${borrowed.map((id) => `'${id}'`).join(", ")}] RETURN c.id;`);
  }
  return L.join("\n") + "\n";
}

// Dublin Core terms a class property may be named for. A property with one of these names means
// what Dublin Core means by it (publication's title, creator, issued...), so it expands to the
// dcterms IRI rather than a private one.
const DCTERMS = new Set(["title", "creator", "publisher", "issued", "modified", "language", "rights", "description", "identifier", "source"]);

export function buildContext(ont, layer = { own: ont, imported: { classes: [], predicates: [], edges: [], layers: [] } }) {
  // The context covers imported terms as well as own ones: an L2 document names an l1:citation as
  // the target of citesSource, and a context that could not expand it would make the cross-layer
  // edge unreadable to any JSON-LD processor.
  const scope = scopeOf(layer);
  const aliases = {};
  for (const c of scope.classes.values()) aliases[camel(c.name)] = `sgkg:${c.id}`;
  const predicates = {};
  // A predicate expands to the IRI the ontology declares for it (every one in this repository is
  // sgkg:<predicate> today); an undeclared term in `predicate` would otherwise expand to nothing.
  for (const p of scope.predicates.values()) predicates[p.predicate] = { "@id": p.iri ?? `sgkg:${p.predicate}` };
  // `properties` is a node with its OWN context, so every property keeps its name as RDF.
  //
  // It was an @index container: `"pageRange": "11-12"` expanded to `sgkg:properties "11-12"`, and
  // the name -- the only thing that says what "11-12" is -- was dropped. @nest (attach each property
  // straight to the node) is NOT safe here: L2 and L3 classes have properties named `source` and
  // `type`, which the document level already defines as rdf:subject and @type, and JSON-LD
  // processors ignore a scoped context on a @nest term (measured with jsonld.js). So the nested
  // object gets its own vocabulary: any property name the document level also uses is redefined
  // to sgkg:<name> inside it, Dublin Core names go to dcterms, and everything else falls to @vocab.
  const docTerms = new Set(["id", "type", "label", "properties", "nodes", "edges", "predicate", "source", "target",
    "qualifier", "derivation", "evidence", "location", "quote", "note", "skill", "generatedAt", "wasDerivedFrom", "ontologyVersion"]);
  const propertyTerms = { "@vocab": ont.namespace };
  for (const c of scope.classes.values()) {
    for (const name of c.properties ?? []) {
      if (DCTERMS.has(name)) propertyTerms[name] = `dcterms:${name}`;
      else if (docTerms.has(name) || name in predicates || name in aliases) propertyTerms[name] = `sgkg:${name}`;
    }
  }
  return {
    "@context": {
      "@version": 1.1,
      rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
      rdfs: "http://www.w3.org/2000/01/rdf-schema#",
      owl: "http://www.w3.org/2002/07/owl#",
      skos: "http://www.w3.org/2004/02/skos/core#",
      dcterms: "http://purl.org/dc/terms/",
      prov: "http://www.w3.org/ns/prov#",
      xsd: "http://www.w3.org/2001/XMLSchema#",
      sgkg: ont.namespace,
      // A node's `type` is a class id ("publication-section"), and the class's IRI is
      // <namespace><id>. Without @vocab the id expands to nothing and every node loses its class.
      "@vocab": ont.namespace,
      id: "@id",
      type: "@type",
      label: { "@id": "rdfs:label" },
      properties: { "@id": "sgkg:properties", "@context": propertyTerms },
      nodes: { "@id": "sgkg:node", "@container": "@set" },
      edges: { "@id": "sgkg:edge", "@container": "@set" },
      Statement: "rdf:Statement",
      Entity: "prov:Entity",
      predicate: { "@id": "rdf:predicate", "@type": "@vocab" },
      source: { "@id": "rdf:subject", "@type": "@id" },
      target: { "@id": "rdf:object", "@type": "@id" },
      qualifier: { "@id": "sgkg:qualifier" },
      derivation: { "@id": "sgkg:derivation" },
      evidence: { "@id": "sgkg:evidence" },
      location: { "@id": "sgkg:location" },
      quote: { "@id": "sgkg:quote" },
      note: { "@id": "skos:note" },
      skill: { "@id": "sgkg:skill" },
      generatedAt: { "@id": "prov:generatedAtTime", "@type": "xsd:dateTime" },
      wasDerivedFrom: { "@id": "prov:wasDerivedFrom", "@type": "@id" },
      ontologyVersion: { "@id": "sgkg:ontologyVersion" },
      ...predicates,
      ...aliases,
    },
  };
}

export function buildTurtle(ont, layer = { own: ont, imported: { classes: [], predicates: [], edges: [], layers: [] } }) {
  const NS = ont.namespace;
  // The ontology IRI and every owl:imports target are built from the layer's FILE NAME, not from
  // its `layer` label. They differ in case ("l2" vs "L2"), and an import naming an IRI no file
  // declares resolves to nothing -- silently, since a reasoner just finds an empty ontology.
  const ontologyIri = (name) => `${NS.replace(/\/$/, "")}/${name}`;
  const selfName = (ont.layer ?? "").toLowerCase();
  // Edge sub-properties need the name of every class an edge touches, imported ones included.
  const byId = scopeOf(layer).classes;
  const ownIds = new Set(ont.classes.map((c) => c.id));
  const T = [
    `@prefix sgkg: <${NS}> .`,
    "@prefix owl:  <http://www.w3.org/2002/07/owl#> .",
    "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
    "@prefix skos: <http://www.w3.org/2004/02/skos/core#> .",
    "",
    `<${ontologyIri(selfName)}> a owl:Ontology ;`,
    ...layer.imported.layers.map((l) => `  owl:imports <${ontologyIri(l)}> ;`),
    `  rdfs:label "WHO SMART Guidelines ${(ont.layer ?? "").toUpperCase()} ontology" ;`,
    `  rdfs:comment "${tt(ont.note ?? "")} Pairwise licensing is carried as sub-properties, ` +
      `because a relationship is licensed between specific class pairs while an OWL object ` +
      `property has one global domain and range." .`,
    "",
    "### Node kinds", "",
  ];

  const KIND_NOTES = {
    // L1
    Source: "A published document, or a part of one, that guidance is stated in.",
    Concept: "A thing the guidance is about.",
    Reference: "A pointer out of this graph. Carries identity only; asserts nothing about the target.",
    // L2 -- the DAK component layer
    Kit: "A Digital Adaptation Kit as a whole: metadata, and the nine components it contains.",
    Component: "One of the nine components DAK.fsh declares a kit must be able to hold. It points at the file that defines it and does not describe that file's interior.",
    Element: "A structured part of a component -- a requirement statement, a task entry. It exists as a node only where something outside its component needs to reach it.",
    // L2-BPMN and L2-DMN -- the file-interior subgraphs
    Artefact: "A file, addressed as a whole. Shares its IRI with the L1 reference to the same file, so opening a file does not create a second name for it.",
    Structure: "An element inside a file. It has no identity apart from the file that contains it, and its vocabulary is the file format's, not WHO's.",
    // L3 -- the FHIR index. FHIR's own split between knowledge artefacts and conformance resources.
    Knowledge: "A FHIR knowledge artefact: something that encodes clinical or operational logic. Indexed by canonical URL; its interior stays in FHIR.",
    Conformance: "A FHIR conformance or definitional resource: something that constrains or defines structure and terminology. Indexed by canonical URL; its interior stays in FHIR.",
  };
  const kinds = [...new Set(ont.classes.map((c) => c.kind))].sort();
  const undescribed = kinds.filter((k) => !(k in KIND_NOTES));
  if (undescribed.length) {
    // A kind that fell through used to render as rdfs:comment "<its own name>", which reads like a
    // description and is not one. Fail instead of emitting it.
    throw new Error(
      `no description for node kind(s) ${undescribed.join(", ")} in build-exports.mjs KIND_NOTES. ` +
      `Add one; a kind is the top of the class hierarchy and an empty gloss propagates everywhere.`);
  }
  for (const kind of kinds) {
    T.push(`sgkg:${kind} a owl:Class ; rdfs:label "${tt(kind)}" ; ` +
           `rdfs:comment "${tt(KIND_NOTES[kind])}" .`);
  }
  T.push("", "### Classes", "");

  for (const c of ont.classes) {
    T.push(`sgkg:${camel(c.name)} a owl:Class ;`);
    T.push(`  rdfs:subClassOf sgkg:${c.kind} ;`);
    T.push(`  rdfs:label "${tt(c.name)}" ;`);
    T.push(`  skos:notation "${c.id}" ;`);
    if (c.elaborates && byId.has(c.elaborates)) {
      // Same resource, described at two layers. owl:equivalentClass would be wrong -- not every
      // external artifact is a decision table -- so this is a subclass plus a note on the practice.
      T.push(`  rdfs:subClassOf sgkg:${camel(byId.get(c.elaborates).name)} ;`);
      T.push(`  skos:note "Instances share the IRI of the ${tt(byId.get(c.elaborates).name)} they ` +
             `elaborate: one artefact, one address, described opaquely at the layer above and ` +
             `structurally here." ;`);
    }
    T.push(`  rdfs:comment "${tt(c.note ?? `${c.archimateType ?? ""} ${c.archimateId ?? ""}`.trim())}" .`);
    T.push("");
  }

  // Value sets are closed code lists bound to class properties; validate.mjs rejects any other
  // value. They go out as SKOS so a reader in Protege sees the vocabulary, not just its name.
  if ((ont.valueSets ?? []).length) {
    T.push("### Value sets", "# Closed code lists bound to class properties. tools/validate.mjs rejects any other value.", "");
    const boundTo = new Map();
    for (const c of scopeOf(layer).classes.values()) {
      for (const [prop, binding] of Object.entries(c.valueSets ?? {})) {
        const { set } = bindingOf(binding);
        if (!boundTo.has(set)) boundTo.set(set, []);
        boundTo.get(set).push(`${c.id}.${prop}`);
      }
    }
    for (const v of ont.valueSets) {
      const scheme = `${NS}valueset/${v.id}`;
      T.push(`<${scheme}> a skos:ConceptScheme ;`);
      T.push(`  skos:notation "${tt(v.id)}" ;`);
      if (v.source) T.push(`  skos:note "source: ${tt(v.source)}" ;`);
      if (boundTo.has(v.id)) T.push(`  skos:note "bound to: ${boundTo.get(v.id).join(", ")}" ;`);
      T.push(`  rdfs:comment "${tt(v.note ?? "")}" .`);
      for (const c of v.codes) {
        T.push(`<${scheme}#${c.code}> a skos:Concept ; skos:inScheme <${scheme}> ; ` +
               `skos:notation "${tt(c.code)}" ; skos:definition "${tt(c.definition ?? "")}" .`);
      }
      T.push("");
    }
  }

  T.push("### Object properties (the ArchiMate relationship vocabulary)", "");
  const used = new Set(ont.edges.map((e) => e.predicate));
  for (const p of ont.predicates) {
    T.push(`sgkg:${p.predicate} a owl:ObjectProperty ;`);
    T.push(`  rdfs:label "${p.predicate}" ;`);
    T.push(`  rdfs:comment "${tt(p.note ?? p.archimateType ?? "")}` +
           `${used.has(p.predicate) ? "" : " -- declared but unused by the current model"}" .`);
    T.push("");
  }

  T.push(
    "### Licensed edges, as qualified sub-properties",
    "# One per (source class, predicate, target class) triple the ArchiMate model licenses.",
    "# Domain and range on the sub-property is what preserves pairwise licensing: a single global",
    "# domain/range on sgkg:associatedWith would be a union of everything and would permit",
    "# Business Process aggregates Data Element, which the model does not.",
    "");

  const seen = new Map();
  for (const e of ont.edges) {
    const s = byId.get(e.source);
    const t = byId.get(e.target);
    const base = `${e.predicate}_${camel(s.name)}_${camel(t.name)}`;
    const n = seen.get(base) ?? 0;
    seen.set(base, n + 1);
    const name = n === 0 ? base : `${base}_${n + 1}`;
    T.push(`sgkg:${name} a owl:ObjectProperty ;`);
    T.push(`  rdfs:subPropertyOf sgkg:${e.predicate} ;`);
    T.push(`  rdfs:domain sgkg:${camel(s.name)} ;`);
    T.push(`  rdfs:range sgkg:${camel(t.name)} ;`);
    if (e.qualifier) T.push(`  skos:note "qualifier: ${tt(e.qualifier)}" ;`);
    if (e.access) T.push(`  skos:note "access: ${e.access}" ;`);
    T.push(`  rdfs:label "${tt(s.name)} ${tt(e.qualifier ?? e.predicate)} ${tt(t.name)}" .`);
    T.push("");
  }
  return T.join("\n") + "\n";
}

// Compare ignoring line endings. The .gitattributes in this repository normalises to LF, but a
// checkout made before it existed -- or with a global core.autocrlf that overrides it -- will have
// CRLF in the working tree. Reporting "stale" at someone who has changed nothing is a check that
// trains people to distrust it, and the newline is not what the check is about.
const sameContent = (a, b) => a.replace(/\r\n/g, "\n") === b.replace(/\r\n/g, "\n");

function main() {
  const check = process.argv.includes("--check");
  let total = 0;

  for (const name of LAYERS) {
    let loaded;
    try {
      loaded = loadLayer(name);
    } catch (err) {
      console.error(err.message);
      process.exit(1);
    }
    const ont = loaded.own;
    const layer = name;
    const dir = layerDir(layer);
    mkdirSync(dir, { recursive: true });
    const outputs = [
      [join(dir, `${layer}.cypher`), buildCypher(ont, loaded)],
      [join(dir, `${layer}.ttl`), buildTurtle(ont, loaded)],
      [join(dir, `${layer}.context.jsonld`), JSON.stringify(buildContext(ont, loaded), null, 2) + "\n"],
    ];

    if (check) {
      for (const [file, want] of outputs) {
        const name = relative(ROOT, file);
        if (!existsSync(file)) {
          console.error(`${name} is missing. Run: node tools/build-exports.mjs`);
          process.exit(1);
        }
        const have = readFileSync(file, "utf8");
        if (!sameContent(have, want)) {
          console.error(`${name} is stale. Run: node tools/build-exports.mjs`);
          process.exit(1);
        }
        if (have !== want) {
          console.warn(
            `warning: ${name} matches but its line endings differ from what the tools write. ` +
            `Run: git add --renormalize .`);
        }
      }
      console.log(`${layer}: exports current -- ${ont.classes.length} classes, ${ont.edges.length} edges` +
                  (loaded.imported.layers.length ? ` (imports ${loaded.imported.layers.join(", ")})` : ""));
    } else {
      for (const [file, text] of outputs) writeFileSync(file, text, "utf8");
      console.log(`${layer}: wrote ${layer}/${layer}.{cypher,ttl,context.jsonld} -- ` +
                  `${ont.classes.length} classes, ${ont.edges.length} edges` +
                  (loaded.imported.layers.length ? ` (imports ${loaded.imported.layers.join(", ")})` : ""));
    }
    total += ont.edges.length;
  }
  // Everything in one file, in dependency order. This is what to hand Neo4j or Protege when you
  // want the whole model and not one subgraph.
  const combined = [
    [join(ROOT, "ontology", "all.cypher"),
     ["// WHO SMART Guidelines knowledge graph -- ALL LAYERS, in dependency order.",
      "// Generated by tools/build-exports.mjs. Do not edit; edit the per-layer JSON.",
      "//",
      "// RUN AGAINST A USER DATABASE, NOT `system`:",
      "//     :use neo4j                              (Neo4j Browser, or your database's name)",
      "//     cypher-shell -d neo4j -f ontology/all.cypher",
      "//",
      "// In Neo4j Browser, turn on \"Enable multi statement query editor\" in Settings before",
      "// pasting -- otherwise only the first statement runs.",
      "//",
      `// ${LAYERS.join(" -> ")}. Loading a layer before the ones it imports silently drops the`,
      "// edges that reach into them, because Cypher does not treat an empty MATCH as an error.",
      "",
      // The constraint is identical in every layer and IF NOT EXISTS makes repeats harmless, but
      // a file handed to someone should not repeat itself four times.
      ...LAYERS.map((l, i) => {
        const t = readFileSync(join(layerDir(l), `${l}.cypher`), "utf8");
        return i === 0 ? t
          : t.replace(/^CREATE CONSTRAINT[^\n]*\nFOR [^\n]*\n\n/m, "");
      }),
     ].join("\n")],
    [join(ROOT, "ontology", "all.ttl"),
     ["# WHO SMART Guidelines knowledge graph -- ALL LAYERS merged.",
      "# Generated by tools/build-exports.mjs. Do not edit; edit the per-layer JSON.",
      "#",
      "# The per-layer files declare owl:imports, which a reasoner can only follow if the IRIs",
      "# resolve. This merge is for opening the whole model offline.",
      "",
      ...LAYERS.map((l, i) => {
        const t = readFileSync(join(layerDir(l), `${l}.ttl`), "utf8");
        // Prefixes are identical across layers; keep one copy so the merge parses.
        return i === 0 ? t : t.replace(/^@prefix[^\n]*\n/gm, "");
      }),
     ].join("\n")],
  ];
  for (const [file, text] of combined) {
    const name = relative(ROOT, file);
    if (check) {
      if (!existsSync(file)) { console.error(`${name} is missing. Run: node tools/build-exports.mjs`); process.exit(1); }
      if (!sameContent(readFileSync(file, "utf8"), text)) {
        console.error(`${name} is stale. Run: node tools/build-exports.mjs`);
        process.exit(1);
      }
    } else {
      writeFileSync(file, text, "utf8");
    }
  }
  console.log(check ? "all.cypher, all.ttl: current" : "wrote all.cypher, all.ttl");

  if (!total) { console.error("no edges exported"); process.exit(1); }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
